### PR TITLE
ECOSYS-103 Add custom JDK path to Payara Server

### PR DESCRIPTION
**Pull request by jGauravGupta**
# Description
This is a feature to update the JDK Home path of the registered Payara Server instance in VSCode

# Test
- Install Node, NPM, and Yarn
- Open a terminal and run `yarn install`  to install all dependencies for the project.
- Run `code .` command from the terminal to open the project in VS Code.
- Press `F5` from Code to run the project which will start another instance of Code with an installed plugin.
- Press `Ctrl + Shift + P` and search for `Add Payara Server` option.
- Right-click on the server to update the JDK path from the context menu.

### CODE REVIEW

**Comment by MattGill98** [comment]
I'm a little confused by this, what are my options for JDK versions, I only seem to see 1? Why is each server linked to its own JDK? I would expect something similar to the configuration option for other extensions:

image

I'm not sure if this is a related issue, but the Payara Server list seems to be wiped every time you open a new project?

**Comment by jGauravGupta** [comment]
Hi @MattGill98,

By default, Each server instance linked to default JDK Home and developers may also customize JDK Home path per registred instance similar to Payara Server support in other IDEs. Using VSCode Settings Preference for JDK Path customization can not be used in such a case as it is used for global configuration not per Payara Server instance.

> I'm not sure if this is a related issue, but the Payara Server list seems to be wiped every time you open a new project?

Payara Server list info stored to per workspace config (`context.storagePath`) instead of global config (`context.globalStoragePath`).
https://github.com/payara/ecosystem-vscode-plugin/blob/master/src/main/fish/payara/server/PayaraInstanceProvider.ts#L47-L68

**Comment by MattGill98** [comment]
The settings similarly aren't contained in the workspace settings page, but I don't know the VSCode plugin authoring well enough to comment on why. On a side note, I can't think of any good reason why this would be a workspace level concern, why shouldn't the installed servers be global?

My first question was relating to the selectable JDK options. Where is this list stored and saved from?

image

**Comment by jGauravGupta** [comment]
>  On a side note, I can't think of any good reason why this would be a workspace level concern, why shouldn't the installed servers be global?

Thanks for your view, I will update it to global.


> My first question was relating to the selectable JDK options. Where is this list stored and saved from?

The list is not saved anywhere and has only 2 value default Java Home path and previously selected value.

**Pull request merged**
